"""The family each kind of defect belongs to.

A finding and a label agree at the family rung when their kinds share a family,
so this one table is read for both. It holds every kind the prompt can name and
the kinds an answer key uses that the prompt does not offer.
"""
from __future__ import annotations

FAMILIES = {
    "missing_authz_check": "authz",
    "crossfile_ownership": "authz",
    "crossfile_data_exposure": "disclosure",
    "crossfile_error_propagation": "error_handling",
    "crossfile_idempotency": "concurrency",
    "crossfile_ordering": "concurrency",
    "crossfile_unit_mismatch": "data_layer",
    "sql_injection": "injection",
    "command_injection": "injection",
    "xss": "injection",
    "error_detail_disclosure": "disclosure",
    "hardcoded_credential": "secrets",
    "weak_crypto_primitive": "crypto",
    "unvalidated_passthrough": "correctness",
    "wrong_argument": "correctness",
    "wrong_data_source": "data_layer",
    "wrong_state_check": "correctness",
    "silent_overwrite": "data_layer",
    "unreachable_code": "maintainability",
    "unused_symbol": "maintainability",
    "misleading_name": "maintainability",
    "duplicated_block": "maintainability",
    "duplicated_config": "config",
    "duplicated_test_block": "test_quality",
    "broad_except": "error_handling",
    "swallowed_exception": "error_handling",
    "unclosed_resource": "resource_perf",
    "redundant_work": "resource_perf",
    "work_in_loop": "resource_perf",
    "removed_dependency": "config",
    "missing_assertion": "test_quality",
    "hardcoded_endpoint": "test_quality",
    "null_deref": "edge_cases",
    "off_by_one": "edge_cases",
    "unguarded_dict_access": "edge_cases",
    "missing_lock": "concurrency",
    "secret_in_log": "secrets",
    "ssrf_unvalidated_fetch": "ssrf",
    "unsafe_deserialization": "deserialization",
    "divergent_change": "maintainability",
    "path_traversal": "injection",
    "open_redirect": "injection",
    "mass_assignment": "authz",
    "unbounded_resource": "resource_perf",
    "float_money": "correctness",
    "naive_datetime": "correctness",
    "blocking_call_in_async": "concurrency",
    "mutable_default_argument": "correctness",
    "regex_denial_of_service": "resource_perf",
    "breaking_public_api": "maintainability",
    "missing_migration": "data_layer",
    "wrong_assertion_target": "test_quality",
    "leaky_test_state": "test_quality",
    "unsafe_default": "config",
    "contradictory_setting": "config",
    "removed_config_key": "config",
    "missing_timeout": "resource_perf",
    "missing_transaction": "data_layer",
    "retry_without_bound": "concurrency",
    "dynamic_code_execution": "injection",
    "insecure_transport": "crypto",
    "unawaited_coroutine": "concurrency",
    "disabled_test": "test_quality",
    "global_state_mutation": "concurrency",
    "lossy_conversion": "correctness",
    "encoding_assumption": "correctness",
    "unsafe_temp_file": "disclosure",
    "ignored_return_value": "error_handling",
    "stale_cache_write": "data_layer",
    "overly_permissive_permission": "authz",
    "insecure_randomness": "crypto",
    "loop_without_progress": "correctness",
    "check_then_act_race": "concurrency",
    "missing_duplicate_guard": "concurrency",
    # Used by an answer key, not offered by the prompt.
    "business_logic": "business_logic",
    "removed_network_config": "config",
}


def family(kind: str) -> str:
    """The family of a kind, or "" for a kind the table does not know -- which matches nothing."""
    return FAMILIES.get(kind, "")
